name: "💎 Code Quality"
on:
  workflow_dispatch:
  workflow_call:

jobs:
  code_quality:
    name: "🛠️ Build & 🧪 Test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: 📦 Install dependencies
        run: npm ci

      - name: 🧪 Run Unittests
        run: xvfb-run --auto-servernum npm run test

      - name: 🧪 Run Integrationtests
        run: xvfb-run --auto-servernum npm run e2e-test

      - name: 🧪 Test Building of Artifact
        run: npx @vscode/vsce package
